services:
  # 之前的网页服务
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  # 新增的 Java 后台服务
  app:
    build: .  # 告诉 Docker：根据当前的 Dockerfile 自己造一个镜像